### ISSUE TITLE
Döküman destek.

### ISSUE THREAD

**Issue by WormerKing** [BAHADIR54/ruby-tutorial#3]
Merhaba hocam ben sizin projenize destek olmak istiyorum.
Acaba yaptığım işlem doğrumudur daha yeni github kullanıyorum.

**Comment by BAHADIR54** [comment]
merhaba iyi gunler evet yardimci olabilirsiniz belli bir standartlarda markdown yazmaniz lazim bu konu hakkinda bana mail yazabilirsiniz daha detayli konusuruz
